[general]
live_config_reload = true

[window]
decorations = "Full"
opacity = 0.8
blur = true
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "None"
option_as_alt = "Both"

[font]
normal = { family = "RecMonoCasual Nerd Font", style = "Regular" }
size = 13
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#CC0000"
green = "#4E9A06"
yellow = "#C4A000"
blue = "#3465A4"
magenta = "#B124C9"
cyan = "#06989A"
white = "#D3D7CF"

[colors.bright]
black = "#5D5F5B"
red = "#EF2929"
green = "#8AE234"
yellow = "#FCE94F"
blue = "#739FCF"
magenta = "#FF00E3"
cyan = "#34E2E2"
white = "#EEEEEC"

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "Never" }

[terminal]
shell = "zellij"

[mouse]
hide_when_typing = false
