name: build
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'custom-prompt/*.c'
  workflow_dispatch:

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: cd custom-prompt && make release
