name: build
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'custom-prompt/*.c'
  workflow_dispatch:

jobs:
  build_linux:
    name: build on ubuntu-22.04
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: custom-prompt
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt install libnotify-dev
      - run: make -j release
  build_windows:
    name: build on windows-2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd custom-prompt
          make -j release CC=gcc
  build_other:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd custom-prompt
          make -j release
