name: package
on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-22.04, windows-2022]
    defaults:
      run:
        working-directory: custom-prompt
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt install libnotify-dev
      - run: make -j release CC=gcc
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: 'custom-prompt/*.tgz'

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: ls *
