name: package
on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  build_macos_windows:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: make -j release CC=gcc
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: 'custom-prompt/bin'

  build_linux:
    name: build on ${{ matrix.arch }}/debian:12
    runs-on: ubuntu-22.04
    container: ${{ matrix.arch }}/debian:12
    strategy:
      matrix:
        arch: [i386, amd64]
    steps:
      - run: apt update && apt install -y build-essential git libnotify-dev libx11-dev
      - uses: actions/checkout@v1
      - run: make -j release
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.arch }}
          path: 'custom-prompt/bin'

  temp:
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/download-artifact@v1
        with:
          name: [i386, amd64]
      - run: |
          ls -l

  release:
    if: github.ref_type == 'tag'
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: chmod +x . -R
      - run: tar czf custom-prompt-amd64-macos.tgz *
        working-directory: macos-13
      - run: tar czf custom-prompt-aarch64-macos.tgz *
        working-directory: macos-14
      - run: tar czf custom-prompt-amd64-linux.tgz *
        working-directory: ubuntu-22.04
      - run: tar czf custom-prompt-amd64-windows.tgz *
        working-directory: windows-2022
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} -n 'Release intended as proof-of-concept. Binaries are dynamically-linked.'
          gh release upload ${{ github.ref_name }} */*.tgz
