name: package
on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  build_macos_windows:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: make -j release CC=gcc
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: 'custom-prompt/bin'

  build_linux:
    name: build on ${{ matrix.arch }}/debian:12
    runs-on: ubuntu-22.04
    container: ${{ matrix.arch }}/debian:12
    strategy:
      matrix:
        arch: [amd64, i386]
    steps:
      - uses: actions/checkout@v1
      - run: |
          apt update
          apt install -y gcc libnotify-dev libx11-dev make
          make -j release
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: 'custom-prompt/bin'

  temp:
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -l $(find . -type f)

  release:
    if: github.ref_type == 'tag'
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/download-artifact@v1
        with:
          name: amd64
      - uses: actions/download-artifact@v1
        with:
          name: i386
      - run: chmod +x . -R
      - run: tar vczf custom-prompt-amd64-macos.tgz *
        working-directory: macos-13
      - run: tar vczf custom-prompt-aarch64-macos.tgz *
        working-directory: macos-14
      - run: tar vczf custom-prompt-amd64-windows.tgz *
        working-directory: windows-2022
      - run: tar vczf custom-prompt-amd64-linux.tgz *
        working-directory: amd64
      - run: tar vczf custom-prompt-i386-linux.tgz *
        working-directory: i386
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} -n 'Release intended as proof-of-concept. Binaries are dynamically-linked.'
          gh release upload ${{ github.ref_name }} */*.tgz
        env:
          GH_TOKEN: ${{ github.token }}
