name: package
on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  build_macos_windows:
    name: build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [{name: 'macos-13', id: 'amd64-macos'}, {name: 'macos-14', id: 'aarch64-macos'}, {name: 'windows-2022', id: 'amd64-windows'}]
    steps:
      - uses: actions/checkout@v4
      - run: make -j release CC=gcc
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v3
        with:
          name: custom-prompt-${{ matrix.os.id }}
          path: 'custom-prompt/bin'

  build_linux:
    name: build on ${{ matrix.arch }}/${{ matrix.os.name }}:${{ matrix.os.tag }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.arch }}/${{ matrix.os.name }}:${{ matrix.os.tag }}
    strategy:
      matrix:
        arch: [amd64, i386]
        os: [{name: 'alpine', tag: '3.20', libc: 'musl'}, {name: 'debian', tag: '12', libc: 'gnu'}]
    steps:
      - if: matrix.os.name == 'alpine'
        run: apk add build-base libnotify-dev libx11-dev
      - if: matrix.os.name == 'debian'
        run: apt update && apt install -y build-essential git libnotify-dev libx11-dev
      - uses: actions/checkout@v1
      - run: make -j release
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v1
        with:
          name: custom-prompt-${{ matrix.arch }-linux-${{ matrix.os.libc }}
          path: 'custom-prompt/bin'

  temp:
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          chmod --recursive +x .
          for package_directory in custom-prompt-*
          do
              file $package_directory/*
          done

  release:
    if: github.ref_type == 'tag'
    needs: [build_macos_windows, build_linux]
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - run: chmod +x . -R
      - run: tar vczf custom-prompt-amd64-macos.tgz *
        working-directory: macos-13
      - run: tar vczf custom-prompt-aarch64-macos.tgz *
        working-directory: macos-14
      - run: tar vczf custom-prompt-amd64-windows.tgz *
        working-directory: windows-2022
      - run: tar vczf custom-prompt-amd64-linux-musl.tgz *
        working-directory: amd64-alpine
      - run: tar vczf custom-prompt-amd64-linux-glibc.tgz *
        working-directory: amd64-debian
      - run: tar vczf custom-prompt-i386-linux-musl.tgz *
        working-directory: i386-alpine
      - run: tar vczf custom-prompt-i386-linux-glibc.tgz *
        working-directory: i386-debian
      - run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} -n 'Release intended as proof-of-concept. Binaries are dynamically-linked.'
          gh release upload ${{ github.ref_name }} */*.tgz
        env:
          GH_TOKEN: ${{ github.token }}
