name: package
on:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  build_macos:
    name: build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [{name: 'macos-13', id: 'amd64-macos'}, {name: 'macos-14', id: 'aarch64-macos'}]
    steps:
      - uses: actions/checkout@v4
      - run: brew install libgit2
      - run: make -j release
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v4
        with:
          name: custom-prompt-${{ matrix.os.id }}
          path: 'custom-prompt/bin'

  build_linux:
    name: build on ${{ matrix.arch }}/${{ matrix.os.name }}:${{ matrix.os.tag }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.arch }}/${{ matrix.os.name }}:${{ matrix.os.tag }}
    strategy:
      matrix:
        arch: [amd64]
        os: [{name: 'alpine', tag: '3.20', libc: 'musl'}, {name: 'debian', tag: '12', libc: 'gnu'}]
    steps:
      - if: matrix.os.name == 'alpine'
        run: apk add build-base libgit2-dev libnotify-dev libx11-dev
      - if: matrix.os.name == 'debian'
        run: apt-get update && apt-get install -y build-essential libgit2-dev  libnotify-dev libx11-dev
      - uses: actions/checkout@v4
      - run: make -j release
        working-directory: custom-prompt
      - uses: actions/upload-artifact@v4
        with:
          name: custom-prompt-${{ matrix.arch }}-linux-${{ matrix.os.libc }}
          path: 'custom-prompt/bin'
