name: style
on:
  push:
    paths:
      - '.github/workflows/style.yml'
      - 'custom-prompt/*.c'
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cd custom-prompt && ./clang-format.bash check
