name: style
on:
  push:
    paths:
      - '.github/workflows/style.yml'
      - 'custom-prompt/*'
  workflow_dispatch:

jobs:
  check:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./clang-format.bash check
        working-directory: custom-prompt

  format:
    if: github.ref_name != github.event.repository.default_branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - run: |
          ./clang-format.bash
          git config user.name 'tfpf'
          git config user.email '19171016+tfpf@users.noreply.github.com'
          git commit -am 'Formatted' && git push || true
        working-directory: custom-prompt
        name: Format C and C++ headers and sources, commit, and push
