name: style
on:
  push:
    paths:
      - '.github/workflows/style.yml'
      - 'custom-prompt/*'
      - 'diff/*'
  workflow_dispatch:

jobs:
  check-diff:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install --global hatch
          hatch fmt --check
        working-directory: diff
        name: Check if Python source is formatted correctly

  check-custom-prompt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./clang-format.bash check
        working-directory: custom-prompt
        name: Check if C and C++ headers and sources are formatted correctly

  format-custom-prompt:
    if: github.ref_type != 'tag' && github.ref_name != github.event.repository.default_branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - run: |
          ./clang-format.bash
          git config user.name 'Github Actions'
          git config user.email '19171016+tfpf@users.noreply.github.com'
          git commit -am 'Formatted' && git push || true
        working-directory: custom-prompt
        name: Format C and C++ headers and sources, commit, and push
